name: Run Stripe Customer Billing Notebook Every 2 Hours

on:
  push:
    paths:
      - 'API_stripe_cutomer_billing.ipynb'
  schedule:
    # Every 2 hours (UTC)
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --quiet \
            papermill \
            nbconvert \
            stripe \
            psycopg2-binary \
            pandas \
            numpy \
            sqlalchemy

      - name: Execute notebook
        run: |
          papermill \
            API_stripe_cutomer_billing.ipynb \
            API_stripe_cutomer_billing.ipynb \
            --log-output

      - name: Upload executed notebook
        uses: actions/upload-artifact@v4
        with:
          name: stripe-billing-notebook
          path: API_stripe_cutomer_billing.ipynb
