name: Run Stripe Customer Billing Notebook Every 2 Hours

on:
  push:
    paths:
      - 'API_stripe_cutomer_billing.ipynb'
  schedule:
    - cron: '0 */2 * * *'   # every 2 h UTC
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install runtime & Jupyter deps
        run: |
          pip install --upgrade pip
          pip install \
            papermill \
            nbconvert \
            ipykernel \
            stripe \
            psycopg2-binary \
            pandas \
            numpy \
            sqlalchemy

      - name: Register a python3 kernel
        run: |
          python -m ipykernel install \
            --user \
            --name python3 \
            --display-name python3

      - name: Execute notebook via Papermill
        run: |
          TS=$(date -u +'%Y%m%dT%H%M%SZ')
          papermill \
            API_stripe_cutomer_billing.ipynb \
            API_stripe_cutomer_billing_out_${TS}.ipynb \
            --kernel python3 \
            --log-output

      - name: Upload executed notebook
        uses: actions/upload-artifact@v4
        with:
          name: stripe-billing-notebooks
          path: API_stripe_cutomer_billing_out_*.ipynb
