name: "Run JustCallAPICall Today Every Day 05:15 AM IST"

on:
  schedule:
    # 05:15 IST = 23:45 UTC (previous day)
    - cron: '45 23 * * *'
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pandas sqlalchemy psycopg2-binary ipykernel nbconvert \
                      requests papermill nbformat

      - name: Execute notebook & log all cell output
        run: |
          papermill \
            JustCallAPICall_today.ipynb \
            output.ipynb \
            --log-output

      - name: Print final cell output
        run: |
          python - << 'EOF'
          import nbformat

          nb = nbformat.read('output.ipynb', as_version=4)
          last = nb.cells[-1]

          for o in last.get('outputs', []):
              text = o.get('text')
              if text:
                  print("➡ Final cell output:")
                  print(text.strip())
          EOF
