name: Run Sales Dialer Daily at 10 AM IST

on:
  schedule:
    - cron: '30 4 * * *'  # 10:00 AM IST
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install pandas sqlalchemy psycopg2-binary ipykernel nbconvert
          python -m ipykernel install --user --name=python3

      - name: Execute Sales Dialer Notebook
        run: |
          jupyter nbconvert --to notebook \
            --execute SalesDialerAPICall.ipynb \
            --output executed_output.ipynb \
            --ExecutePreprocessor.timeout=600 \
            --ExecutePreprocessor.kernel_name=python3 \
            --debug || true

      - name: Upload Executed Notebook (Even on Error)
        uses: actions/upload-artifact@v4
        with:
          name: executed-output-debug
          path: executed_output.ipynb

