name: Run SalesDialierAPICall Every Day 3:15 AM IST

on:
  schedule:
    - cron: '45 21 * * *'  # 3:15 AM IST = 9:45 PM UTC (previous day)
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pandas sqlalchemy psycopg2-binary ipykernel nbconvert requests
          python -m ipykernel install --user --name=python3

      - name: Execute notebook
        run: |
          jupyter nbconvert --to notebook --execute SalesDialierAPICall.ipynb --output output.ipynb
